package com.fyp.lucapp.Models;
import androidx.annotation.NonNull;
import java.io.Serializable;
import java.sql.Time;
import java.sql.Date;

/**
 * This class is a model class which is used to store the data of the report generated by the doctor
 */
public class Report implements Serializable {
    private String reportID;
    private String patientName;
    private String doctorName;
    private Date reportGenerationDate;
    private Time reportGenerationTime;
    private String descriptionOfAppointment;
    private String detectedImage;

    public Report(String reportID, String patientName,
                  String doctorName, Date reportGenerationDate,
                  Time reportGenerationTime, String descriptionOfAppointment,
                  String detectedImage) {

        this.reportID = reportID;
        this.patientName = patientName;
        this.doctorName = doctorName;
        this.reportGenerationDate = reportGenerationDate;
        this.reportGenerationTime = reportGenerationTime;
        this.descriptionOfAppointment = descriptionOfAppointment;
        this.detectedImage = detectedImage;

    }




    public String getReportID() {
        return reportID;
    }

    public void setReportID(String reportID) {
        this.reportID = reportID;
    }

    public String getPatientName() {
        return patientName;
    }

    public void setPatientName(String patientName) {
        this.patientName = patientName;
    }

    public String getDoctorName() {
        return doctorName;
    }

    public void setDoctorName(String doctorName) {
        this.doctorName = doctorName;
    }

    public Date getReportGenerationDate() {
        return reportGenerationDate;
    }

    public void setReportGenerationDate(Date reportGenerationDate) {
        this.reportGenerationDate = reportGenerationDate;
    }

    public Time getReportGenerationTime() {
        return reportGenerationTime;
    }

    public void setReportGenerationTime(Time reportGenerationTime) {
        this.reportGenerationTime = reportGenerationTime;
    }

    public String getDescriptionOfAppointment() {
        return descriptionOfAppointment;
    }

    public void setDescriptionOfAppointment(String descriptionOfAppointment) {
        this.descriptionOfAppointment = descriptionOfAppointment;
    }

    public String getDetectedImage() {
        return detectedImage;
    }

    public void setDetectedImage(String detectedImage) {
        this.detectedImage = detectedImage;
    }


    @NonNull
    @Override
    public String toString() {
        return "Report{" +
                "appointmentID='" + reportID + '\'' +
                ", patientName='" + patientName + '\'' +
                ", doctorName='" + doctorName + '\'' +
                ", dateOfAppointment='" + reportGenerationDate + '\'' +
                ", timeOfAppointment='" + reportGenerationTime + '\'' +
                ", descriptionOfAppointment='" + descriptionOfAppointment + '\'' +
                ", detectedImage='" + detectedImage + '\'' +
                '}';
    }


}
